### ISSUE TITLE
Propose OSGEO a way of supporting Osgeo4w

### ISSUE THREAD

**Issue by pcav** [qgis/PSC#24]
Send OSGEO a letter explaining our position:
* It’s a “community project” according to https://www.osgeo.org/projects/osgeo4w/ 
* https://wiki.osgeo.org/wiki/OSGeo_Budget_2019 reads “Community projects act through the board as they do not have a project officer. Board approved $1000 for each project (see Community Projects Initiative above)”
Apply for funds.

**Comment by anitagraser** [comment]
I've put a preliminary $4k into https://wiki.osgeo.org/wiki/OSGeo_Budget_2020

**Comment by timlinux** [comment]
How about this draft:


Dear OSGEO Board

We are writing to petition your help both financially and for general support with the OSGEO4W project. Over the years, OSGEO4W (started by Frank Warmerdam and Jürgen Fischer) has become the de-facto delivery mechanism to Windows users for many of the projects that make up OSGEO - including GDAL, PROJ, GRASS, QGIS and many more.

Currently, most of the maintenance and improvements to OSGEO4W are carried out through activities of the QGIS packaging process (our windows standalone packages are based on OSGEO4W). This includes using a portion of the income donated to QGIS.org each year to support the OSGEO4W project.

Since OSGEO4W plays such a central role in the OSGEO landscape we would like to ask you to 'adopt' the OSGEO4W project financially and also help with marshalling more contributors to the project so that it is not a 'one man show' - which represents a vulnerability to the long term prospects of this project. You can see these sentiments reflected in the budget request for supporting OSGEO4W in the OSGEO budget call. This budget request represents 50% of the anticipated budget for funded OSGEO4W work for 2020, with the remainder being funded by QGIS.org for the interim.

Regards

The QGIS team.

**Comment by anitagraser** [comment]
It might be worth mentioning that the requested budget represents 50% of what we think is necessary and that the other 50% will be covered by QGIS.ORG

**Comment by timlinux** [comment]
> It might be worth mentioning that the requested budget represents 50% of what we think is necessary and that the other 50% will be covered by QGIS.ORG

Thanks, done.

**Comment by pcav** [comment]
senti to board@lists.osgeo.org

**Comment by pcav** [comment]
Sent a clear proposal.

**Comment by mbernasocchi** [comment]
@pcav I close this since done. reopen if needed

**Comment by pcav** [comment]
Let's wait for a reply from Osgeo

**Comment by anitagraser** [comment]
Has there been a reply?
