### ISSUE TITLE
Status of & reports on accepted grants 2018

### ISSUE THREAD

**Issue by anitagraser** [qgis/PSC#29]
Deadline
===========
2020-01-31

Notes
=====
There were seven successful proposals, checkmarks indicate finished projects:

- [x] Increased stability for Processing GUI and External Providers (Nyall Dawson) - [Report](https://lists.osgeo.org/pipermail/qgis-psc/2018-September/006601.html)
- [x] OSGeo4W updates (Jürgen Fischer) - without that there wouldn't be any QGIS 3x Windows versions
- [x] Resurrect Processing "R" Provider (Nyall Dawson) - [Announcement ](https://lists.osgeo.org/pipermail/qgis-developer/2018-November/055329.html)- [Plugin website](https://north-road.github.io/qgis-processing-r/) 
- [x] [OpenCL support for processing core algs](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/121) (Alessandro Pasotti) - (https://github.com/qgis/QGIS/pull/7451)
- [x] QGIS server OGC compliant and certified for WFS (Régis Haubourg) - partially completed, ran out of resources ([current status](http://test.qgis.org/ogc_cite/wfs_110/latest/report.html))
- [x] [Charts and drawings on attribute forms](https://gist.github.com/m-kuhn/e530f6e838dbbf608f12f2da39f8a18d#file-charts-and-drawings-attribute-form-md) (Matthias Kuhn) - [The new QML widgets in QGIS](https://www.opengis.ch/2018/11/06/qml-widgets-qgis/) (https://github.com/qgis/QGIS/pull/7801) 
- [ ] Update of QGIS Training Manual (Matteo Ghetta)

**Comment by anitagraser** [comment]
The last status overview I could find was by @pcav https://lists.osgeo.org/pipermail/qgis-psc/2018-September/006556.html

> * increased stability for Processing: unknown
> * OSGeo4W updates: unknown
> * Processing R provider: unknown
> * OpenCL for Processing: completed
> * QGIS server OGC: partly done, resources terminated
> * Charts in forms: completed
> * Training manual: 40% completed

Response by Nyall: https://lists.osgeo.org/pipermail/qgis-psc/2018-September/006601.html

**Comment by andreasneumann** [comment]
They are all completed, except for the last one and the OGC WFS compliance (which ran out of resources).

**Comment by anitagraser** [comment]
@nyalldawson Is there any page I could link to for a summary of the "Increased stability for Processing GUI and External Providers" proposal?

**Comment by nyalldawson** [comment]
@anitagraser 

Here's the text from the report sent to PSC:

"Processing GUI and maintenance work:

- Many bugs in the QGIS 3rd party providers have been fixed, with lots
of new unit tests added. I've cleared out most of the outstanding
issues against the SAGA provider (in most cases adding one or more
test cases for these). I've also refactored the GDAL algorithm tests
to test the GDAL command generated instead of the resultant output.
This allows for much easier test creation (and there's now dozens of
tests covering most of the GDAL algorithms, with tests for all the
individual parameter options for these), and is much easier to detect
when things go wrong vs the old approach of testing the created files.
This also means we're no longer testing GDAL's operation itself, just
making sure that what QGIS sends to GDAL is correct (so the tests are
more robust against different GDAL versions). Additionally, lots of
GRASS unit tests which were disabled in the lead-up to 3.0 have been
resurrected, and we now test have some GRASS vector algorithms unit
tests too. I'll continue to track the different channels for bug
reports against individual algorithms and fix these.

- The GUI refactoring has proceeded nicely, with the new c++ classes
and framework in place for QGIS 3.4. This new framework is soaked in
unit tests. So far the string, CRS and boolean parameters have been
ported to the new API, with numeric and distance parameters ported in
a (currently unmerged) PR. The new API brings many improvements
besides the added stability, and should make it easier to utilise
expression-based parameter values within models and make support for
these automatic for all ported parameter types (vs lots of
duplicate/fragile code in the older Python implementations). The
porting work will continue during freeze and 3.6 (next up are the
file, range and expression parameter widgets)."

There's no blog post write up of this, just the email report.

**Comment by anitagraser** [comment]
@nyalldawson Thank you, Nyall! I was under the impression that those paragraphs were merely a status update for work in progress but if they represent the final report, I'll use them.

**Comment by nyalldawson** [comment]
@anitagraser 

It's a little murky I guess -- that was the report initially sent to PSC, but there has been many follow ups since then. 

E.g. for the gui refactoring, the point parameter, file parameter, range parameter, expression parameter, enum parameter, field parameter and fixed table (matrix) parameters have all been ported to date. Not all of these were part of the original proposal however!

**Comment by anitagraser** [comment]
I've published a summary blog post now: http://blog.qgis.org/2020/01/06/reports-from-the-winning-grant-proposals-2018/

Please let me know if anything should be added or needs correction.

**Comment by pcav** [comment]
Thanks Anita!
