### ISSUE TITLE
AGM 2020: Prepare vote on environmental policy

### ISSUE THREAD

**Issue by andreasneumann** [qgis/PSC#32]
Prepare some votes on environmental policy for AGM 2020

Deadline
===========
2020-02-28

Notes
=====
see e-mail-thread starting at https://lists.osgeo.org/pipermail/qgis-psc/2020-January/008150.html

**Comment by pcav** [comment]
Here a proposed text:
---
* do we need an explicit environmental policy?
  * yes, as an independent document
  * yes, as a part of our social contract/vision/etc
  * no

* how many in-person meetings do we want per year?
  * 0
  * 1
  * 2

* do we want general meetings, or a series of smaller ones in sync, so to minimize total movements and promote participation across the globe?
  * general
  * local

* do we want the participants to travel by train instead of plane?
  * yes, reimbursement will be allowed only for trains and other low impact means (warning: this will essentially ban people from continents other that where we hold the meeting)
  * yes, reimbursement will be allowed for trains and other low impact means; flying will be reimbursed only if
    * distance is more than 1,500 km
    * train will take significantly longer (10 h) than flying
    * cost will be significantly (300 €) lower
  * yes, we will suggest all participants to minimize their impact, leaving the choice to individuals, and reimbursing anyway

**Comment by wonder-sk** [comment]
Few questions:
- do we need an explicit environmental policy - I am not sure I understand the difference between the first two answers (and what are the implications)
- third question - what is meant by "local"? Each country with its own meeting? Or the whole Europe with a single meeting? If the voters choose "local" meetings - are we going to discourage participation of people from outside that region?
- fourth question - there is no "no" answer? :-)
- several questions have multiple answers - is a majority required for a single answer to win? or simply most votes?
- what are impacts of the voting - is it more of a survey or would that be a formal decision that PSC needs to implement?
- can we have also "I don't have an opinion" answer? My feeling is that some people may feel strongly about some questions but not so much about others.

**Comment by pcav** [comment]
1. not much, just an organizational option
2. this has to be flexible, it's a general recommendation
3. right, to be added
4. my interpretation is most votes
5. formal decision by the AGM
6. right, to be added

Thanks for comments!

**Comment by m-kuhn** [comment]
> 4. my interpretation is most votes

If for example, Q1. receives:

-    yes, as an independent document : 16 votes
-    yes, as a part of our social contract/vision/etc : 15 votes
-    no : 20 votes

What will be the result?

**Comment by pcav** [comment]
Good point. As it stand, it would be a no. To be more reasonable, I propose:
* yes 31
 * independent 16
 * contract 15
* no 20
So it would be Yes, independent

**Comment by m-kuhn** [comment]
Thank you, this grouping sounds good to me :+1: 

I thought about it a bit more during the day. Mostly about the other 3 questions. I think there is so much interdependency between these that it's almost impossible to vote on these in one single act. E.g. as a voting member I could have a different opinion on the number of meetings depending on if they are global or local. Or what should I do if I am generally in favor of joining reimbursments with mode of travel, but for whatever reason not with those proposed numbers because, does a No mean "I don't care about the environment" or a "The current means are too strict" or "The current means are too loose".

Taking other democratic processes as an example, there is often a general vote on a concept and then leaving figuring out the details to another instance. This also makes it easier to adjust things down the road if things work different than expected. In this case here we could ask generally 

* I am in favor of attaching the reimbursment process of the contributor meetings to a environmentally sustainable mode of travel. The PSC is mandated to find useful tools and measures.

**Comment by pcav** [comment]
Someone asked to put the question to the AGM precisely because they felt PSC is not the best subject to decide on this.
Of oourse this kind of question is an easy win (who is against being environmentally friendly?), but leaves all the real stuff to the PSC (which I do not oppose).

**Comment by m-kuhn** [comment]
True. But many people also have put forward general doubts about if the QGIS project should really take responsibility for the topic. The question should also come with a short summary describing the risks and potential measures to be taken (just like you wrote them) as examples. I hope that by leaving the precise measures open, it also leaves room for discussion of these.

**Comment by andreasneumann** [comment]
done ... see AGM 2020
