### ISSUE TITLE
Meeting minutes PDFs

### ISSUE THREAD

**Issue by anitagraser** [qgis/PSC#54]
Deadline
===========
2021-01-31

Create PDFs from PSC meeting minutes and link them in https://github.com/qgis/QGIS/wiki

**Comment by timlinux** [comment]
So @seabilwe has kindly 'volunteered' to migrate these. Because we cannot attach pdfs directly in the wiki, I am going to have her do it here and then link to the uploaded attachements from the wiki. Hope that works for you?

@seabilwe please work through the list below. For each doc, save it as a PDF, then attach it to this issue. Then replace the GDrive link with the PDF attachment link. (so we want to keep the original GDoc links too @anitagraser ?)

This is a list of QGIS PSC meeting minutes, available for public reference:

**2021**

- [ ] [January 2021](https://docs.google.com/document/d/1AO8bmkcTJpWVQnU4mYKsobl26d0w5QqAYIaQb_W9_zo/edit?usp=sharing)

**2020**

- [ ] [December 2020](https://docs.google.com/document/d/1me5Mq0bdrkBY2eGA0dKCcquBTvLXN60x-YuIZTc7O1k/edit?usp=sharing)
- [ ] [November 2020](https://docs.google.com/document/d/1593CZz8cyRkoZ_a5g8Pn_HRacNFEjwOGnK6fVR4GtJU/edit?usp=sharing)
- [ ] [October 2020](https://docs.google.com/document/d/18IZ5yOwQma1WRh8FREb5vWaIUGuYwJ0Thqa7hK-pATA/edit?usp=sharing)
- [ ] [September 2020](https://docs.google.com/document/d/1Im-Z83byy1Wz93yd_v91TtkMxhMnsaHUkXwXXDpP924/edit?usp=sharing)
- [ ] [August 2020](https://docs.google.com/document/d/15ayCexymb8WRZdGbQCkIFkYs06UyPO05tbd6za7VPNY/edit?usp=sharing)
- [ ] [July 2020](https://docs.google.com/document/d/1sXZ8KVPcsOQ5GIywRzki2o3uNlECAImgMlT9XJdslSs/edit?usp=sharing)
- [ ] [June 2020](https://docs.google.com/document/d/1nQYoDpPcNUTvqWFMii-G14OS6L7zy9E0pvp_5ILHhQ8/edit?usp=sharing)
- [ ] [May 2020 part 2](https://docs.google.com/document/d/1W6v-1o9yrK2Ac4zvOJAgP35IYVwp1exxfe5VayXi8wA/edit?usp=sharing)
- [ ] [May 2020](https://docs.google.com/document/d/1wgV7oXBJz3zb4eat1532hsb3D38XY87sM9KkkR79tZU/edit?usp=sharing)
- [ ] [April 2020](https://docs.google.com/document/d/1tUbsKOTmj8IJRctlKsx4cktr3_9A52oTRf9DdpydlMg/edit?usp=sharing)
- [ ] [March 2020 part 2](https://docs.google.com/document/d/1jINPb0dQuW2Jqazuux2a_87PjEaO8OSgc8zGb5zCGGE/edit?usp=sharing)
- [ ] [March 2020](https://docs.google.com/document/d/1DtjeRUoq9AMu6urKKuGEuCGc94rKn-y2LK5xMkMgfr4/edit?usp=sharing)
- [ ] [February 2020](https://docs.google.com/document/d/12c9nfVm3hdNx-DQNP8_jq66anpNX8uAW-YIxCtqxJsY/edit?usp=sharing)
- [ ] [January 2020](https://docs.google.com/document/d/1Mvto14JCKmPGk4rouL5bmFykxeBzy86k8WS1FQmyndw/edit?usp=sharing)

**2019**

- [ ] [December 2019](https://docs.google.com/document/d/1mUH4Paoy7-_0lnRPATidlQ_QlmsL7U0gfI5GwLvyhnM/edit?usp=sharing)
- [ ] [November 2019](https://docs.google.com/document/d/1fsSHA1N0KK7enNpXRW3FJ26qa0SY0RHRoOj8_XSMHV8/edit?usp=sharing)
- [ ] [October 2019](https://docs.google.com/document/d/1qeXinguVrNTuRucdqm86Fcunks3UHpEtRi-rO73Dc7o/edit?usp=sharing)
- [ ] [September 2019](https://docs.google.com/document/d/1fecwgBHJ1VOGMpyf5QclIxmLJklvsc5a7Do_qKaWIos/edit?usp=sharing)
- [ ] [August 2019](https://docs.google.com/document/d/1WY2S9IcIwYNUT_kzTrtYbe9ydR4hD35MEvZ75CT7Yg8/edit?usp=sharing)
- [ ] [July 2019](https://docs.google.com/document/d/1gvJVA6FzZhak2W449SdhXVYRXCIv4a2XRjr6MPCdUvw/edit?usp=sharing)
- [ ] [June 2019](https://docs.google.com/document/d/1pUGN5FfUQladPRH2OLPGDjTE6UVtlAvVqZcKn7xIgtM/edit?usp=sharing)
- [ ] [May 2019](https://docs.google.com/document/d/1p5bZ5UCClw9gNX-ecbItIpu4Kk_PRDgU7xUvmlpeiU4/edit?usp=sharing)
- [ ] [April 2019](https://docs.google.com/document/d/10oZxr18jvMcnwSlJZQz1wnTU-5lsKGQrYatDQIjU9XE/edit?usp=sharing)
- [ ] [March 2019](https://docs.google.com/document/d/11rjKqsg4-JqmoGKS8vf_Rb3z3287KkEU4w_C2mwyihQ/edit?usp=sharing)
- [ ] [February 2019](https://docs.google.com/document/d/1whnCeVwlWH9vtgDXOrSCrDt-7U4Tx9brVLP-PYCuBXg/edit?usp=sharing)
- [ ] [January 2019](https://docs.google.com/document/d/1EghTqv5XtNkSUXPAsTPg7RTRcY_bq_8cmIuHZzMwXIQ/edit?usp=sharing)

**2018**

- [ ] [December 2018](https://docs.google.com/document/d/1TeVmd8W-vJ0NxKmrFybcAV4Sxci50WbNGyZhM5F4bZc/edit?usp=sharing)
- [ ] [November 2018](https://docs.google.com/document/d/1XiIQ3Ep-ZGhbc73LA3-eQZteqJ6TfTIBqot48G2VmV0/edit?usp=sharing)
- [ ] [October 2018](https://docs.google.com/document/d/17Lnlx5O9ExwDN5pHx7aOdq9Wl1JYln6p2KFVOcKWioo/edit?usp=sharing)
- [ ] [September 2018](https://docs.google.com/document/d/1wcx1ioYj9kEHQKoNPO95acJPrabkZbeTaOj0GNQ4zI8/edit?usp=sharing)
- [ ] [August 2018](https://docs.google.com/document/d/1P6-3SP_EYHlgo3kvPJQ_sXoFvF6jA91LUiJ45AY6Tfs/edit?usp=sharing)
- [ ] [July 2018](https://docs.google.com/document/d/1ctX0Dxaiqdu8z2Dmwuv3IVQk9r4dhHnbzmfqxKMe_aw/edit?usp=sharing)
- [ ] [June 2018](https://docs.google.com/document/d/1JqvlJRuTKj9q-JETEz6k3tpUzCaZAlrWHB9pyckF_SQ/edit?usp=sharing)
- [ ] [May 2018](https://docs.google.com/document/d/1gdIzwOlzRhy9UHFk_u7LR24j9ZtxTYcOXbhWIgHJs-0/edit?usp=sharing)
- [ ] [April 2018](https://docs.google.com/document/d/1YlQhHUkR0Bo9fzhJUFeHI7Prok5NiytRcFhxRaSgWS0/edit?usp=sharing)
- [ ] [March 2018](https://docs.google.com/document/d/1eU9BV0Ij5sBkxr_oqAkZZtuJQ0BjfXBoGNkNRJ2mUf0/edit?usp=sharing)
- [ ] [February 2018](https://docs.google.com/document/d/199eU5MnL6gNGMJXtChAq2T4_hjtknTGjpYKtYkja4xQ/edit?usp=sharing)
- [ ] [January 2018](https://drive.google.com/open?id=1dwSy6FDq-uzV4OTpGIiLMzBu9FxiyMnpAPQjwwHyn2k)

**2017**

- [ ] [December 2017](https://docs.google.com/document/d/17y78TQUwnml-VVskW1Mg7hvgssmN_6STMZBAuFqY4y0/edit?usp=sharing)
- [ ] [November 2017](https://docs.google.com/document/d/1bUCDUBywqVgu6EqfBwIVoD_HgH7T1LogcFmyHiw1LiI/edit?usp=sharing)
- [ ] [October 2017](https://docs.google.com/document/d/11mLpmyr9mueDv1NgsDLCrD68I9_3WU26pZoCNYUiTbw/edit?usp=sharing)
- [ ] [September 2017](https://docs.google.com/document/d/1c6WHXQUpx_lgU1g1bGjRekTJHMlJeeC3WW7GLMFKSiA/edit?usp=sharing)
- [ ] [August 2017](https://docs.google.com/a/qgis.org/document/d/1u7_dH_PmPj2hxP8_bnrDzL4z7bN7ZyCAT1ZWG4Tyg4M/edit?usp=sharing)
- [ ] [July 2017](https://docs.google.com/document/d/1KF6-FhfIBf8H8NBOJYAfeCg2xBJn17Y1LcpHidhXFC4/edit?usp=sharing)
- [ ] [June 2017](https://docs.google.com/document/d/1s4mTD532sXNDh71mv6y0BQQLwyWKJR-EHO2oLHLY8zw/edit?usp=sharing)
- [ ] [May 2017](https://docs.google.com/document/d/1ue2qhejZIQc-51cLG0k8MHgWP8xW7AeelxfhJZb_zNU/edit?usp=sharing)
- [ ] [April 2017](https://docs.google.com/document/d/1rmzpn5WqNMr48drpPMh-NWtjKXnTgdrrMU36UVt2C5w/edit?usp=sharing)
- [ ] [March 2017](https://docs.google.com/document/d/17rQ1bmnJaTCHxWIumphgiZ0jdBDw-0UBlgRG_rxCe8k/edit?usp=sharing)
- [ ] [February 2017](https://docs.google.com/document/d/1J-4smr-o_xQUoOUvLI1O-ge3sBczElthGwvSZiKU5ZY/edit?usp=sharing)
- [ ] [January 2017](https://docs.google.com/document/d/1OXlR0QBWQRAUYX0g7s72jZ_9hSU_S33FYoN1Iy3-wwE/edit?usp=sharing)

**2016**

- [ ] [December 2016](https://docs.google.com/document/d/1dIEpigSPHH--agbMiBqbRpqTDbmlrNCXUTQkd5Qgxts/edit?usp=sharing)
- [ ] [November 2016](https://docs.google.com/document/d/1STc6beUTtUjA6h_krobsS6F-jFbGVvTGGnGPmGMRtEA/edit?usp=sharing)
- [ ] [October 2016](https://docs.google.com/document/d/1iGxx7N587CxGiXGlVlvrBFW7tVXltY4XXbVogWYJbsg/edit?usp=sharing)
- [ ] [September 2016](https://docs.google.com/document/d/1-VNOuZWnPv7hZTHiGBTTHCskS52t73oKGR0t4A39gd0/edit?usp=sharing)
- [ ] [August 2016](https://docs.google.com/document/d/1-VNOuZWnPv7hZTHiGBTTHCskS52t73oKGR0t4A39gd0/edit?usp=sharing)
- [ ] [July 2016](https://docs.google.com/document/d/1yY8uL4Bw9J5lQHmPOWbMzO4jb5Z9lB4XHp1eWM-c46M/edit?usp=sharing)
- [ ] [June 2016](https://docs.google.com/document/d/19w6A4YQTiM5DRpJiiPRRQx0EJKWKxyBh6az_XYVo1qk/edit?usp=sharing)
- [ ] [May 2016](https://docs.google.com/document/d/1jhQJ-Wo-9GRNrMau4e1znnbNT_JA-ChC8DFUVVE41wM/edit?usp=sharing)
- [ ] [April 2016](https://docs.google.com/document/d/1JEGGXsvj72gZ72PiM6E0KhpUwWbLMCzdUJ4cHFZywjk/edit?usp=sharing)
- [ ] [March 2016](https://docs.google.com/document/d/1arzcgoU0NErm8yiqDvCeasFUdr9zt-8JUx15f3ivTdw/edit?usp=sharing)
- [ ] [February 2016](https://docs.google.com/document/d/15Wulk-d2gOhQixqFZxyfopTuwGXn9EOtG2-gLigV-4c/edit?usp=sharing)
- [x] [January 2016](https://docs.google.com/document/d/1MZQ7CXOBMOuuQVi46TPzueL0LuYTTi4cLFcwN5FA2EE/edit?usp=sharing) PDF: [QGIS-PSC-Meeting-January2016.pdf](https://github.com/qgis/PSC/files/5781396/QGIS-PSC-Meeting-January2016.pdf)

**Comment by seabilwe** [comment]
## 2021 

- [x] [June 2021.pdf](https://github.com/qgis/PSC/files/7656674/June.2021.pdf)
- [x] [July 2021.pdf](https://github.com/qgis/PSC/files/7656675/July.2021.pdf)
- [x] [August 2021.pdf](https://github.com/qgis/PSC/files/7656679/August.2021.pdf)
- [x] [September 2021.pdf](https://github.com/qgis/PSC/files/7656682/September.2021.pdf)
- [x] [October 2021.pdf](https://github.com/qgis/PSC/files/7656683/October.2021.pdf)
- [x] [November 2021.pdf](https://github.com/qgis/PSC/files/7656684/November.2021.pdf)

- [x] [May 2021.pdf](https://github.com/qgis/PSC/files/7453188/May.2021.pdf)
- [x] [April 2021.pdf](https://github.com/qgis/PSC/files/7453180/April.2021.pdf)
- [x] [March 2021.pdf](https://github.com/qgis/PSC/files/7453175/March.2021.pdf)
- [x] [February 2021.pdf](https://github.com/qgis/PSC/files/7453173/February.2021.pdf)
- [x] [QGIS-PSC-Meeting-05-January-2021.pdf](https://github.com/qgis/PSC/files/5867275/QGIS-PSC-Meeting-05-January-2021.pdf)


## 2020
- [x] [QGIS-PSC-Meeting-08-December-2020.pdf](https://github.com/qgis/PSC/files/5867078/QGIS-PSC-Meeting-08-December-2020.pdf)
- [x] [QGIS-PSC-Meeting-03-November-2020.pdf](https://github.com/qgis/PSC/files/5867089/QGIS-PSC-Meeting-03-November-2020.pdf)
- [x]  [QGIS-PSC-Meeting-06-October-2020.pdf](https://github.com/qgis/PSC/files/5867169/QGIS-PSC-Meeting-06-October-2020.pdf)
- [x] [QGIS-PSC-Meeting-01-September-2020.pdf](https://github.com/qgis/PSC/files/5867171/QGIS-PSC-Meeting-01-September-2020.pdf)
- [x] [QGIS-PSC-Meeting-04-August-2020.pdf](https://github.com/qgis/PSC/files/5867179/QGIS-PSC-Meeting-04-August-2020.pdf)
- [x]  [QGIS-PSC-Meeting-07-July-2020.pdf](https://github.com/qgis/PSC/files/5867188/QGIS-PSC-Meeting-07-July-2020.pdf)
- [x] [QGIS-PSC-Meeting-02-June-2020.pdf](https://github.com/qgis/PSC/files/5867196/QGIS-PSC-Meeting-02-June-2020.pdf)
- [x] [QGIS-PSC-Meeting-12-May-2020 part 2.pdf](https://github.com/qgis/PSC/files/5867231/QGIS-PSC-Meeting-12-May-2020.part.2.pdf)
- [x] [QGIS-PSC-Meeting-5-May-2020.pdf](https://github.com/qgis/PSC/files/5867215/QGIS-PSC-Meeting-5-May-2020.pdf)
- [x] [QGIS-PSC-Meeting-7-April-2020.pdf](https://github.com/qgis/PSC/files/5867221/QGIS-PSC-Meeting-7-April-2020.pdf)
- [x] [QGIS-PSC-Meeting-17-March-2020 part 2.pdf](https://github.com/qgis/PSC/files/5867226/QGIS-PSC-Meeting-17-March-2020.part.2.pdf)
- [x] [QGIS-PSC-Meeting-3-March-2020.pdf](https://github.com/qgis/PSC/files/5867249/QGIS-PSC-Meeting-3-March-2020.pdf)
- [x] [QGIS-PSC-Meeting-4-February-2020.pdf](https://github.com/qgis/PSC/files/5867254/QGIS-PSC-Meeting-4-February-2020.pdf)
- [x] [QGIS-PSC-Meeting-7-January-2020.pdf](https://github.com/qgis/PSC/files/5867256/QGIS-PSC-Meeting-7-January-2020.pdf)



## 2019
- [x] [QGIS-PSC-Meeting-3-December-2019.pdf](https://github.com/qgis/PSC/files/5866707/QGIS-PSC-Meeting-3-December-2019.pdf)
- [x] [QGIS-PSC-Meeting-19-November-2019.pdf](https://github.com/qgis/PSC/files/5866721/QGIS-PSC-Meeting-19-November-2019.pdf)
- [x] [QGIS-PSC-Meeting-14-October-2019.pdf](https://github.com/qgis/PSC/files/5866733/QGIS-PSC-Meeting-14-October-2019.pdf)
- [x] [September 2019](url)
- [x] [QGIS-PSC-Meeting-26-August-2019.pdf](https://github.com/qgis/PSC/files/5866743/QGIS-PSC-Meeting-26-August-2019.pdf)
- [x] [QGIS-PSC-Meeting-29-July-2019.pdf](https://github.com/qgis/PSC/files/5866775/QGIS-PSC-Meeting-29-July-2019.pdf)
- [x] [QGIS-PSC-Meeting-10-June-2019.pdf](https://github.com/qgis/PSC/files/5866793/QGIS-PSC-Meeting-10-June-2019.pdf)
- [x] [QGIS-PSC-Meeting-06-May-2019.pdf](https://github.com/qgis/PSC/files/5866801/QGIS-PSC-Meeting-06-May-2019.pdf)
- [x] [QGIS-PSC-Meeting-08-April-2019.pdf](https://github.com/qgis/PSC/files/5866819/QGIS-PSC-Meeting-08-April-2019.pdf)
- [x] [QGIS-PSC-Meeting-08-March-2019.pdf](https://github.com/qgis/PSC/files/5866839/QGIS-PSC-Meeting-08-March-2019.pdf)
- [x] [QGIS-PSC-Meeting-04-February-2019.pdf](https://github.com/qgis/PSC/files/5866929/QGIS-PSC-Meeting-04-February-2019.pdf)
- [x] [QGIS-PSC-Meeting-07-January-2019.pdf](https://github.com/qgis/PSC/files/5866941/QGIS-PSC-Meeting-07-January-2019.pdf)



## 2018
- [x] [QGIS-PSC-Meeting-03-December-2018.pdf](https://github.com/qgis/PSC/files/5866330/QGIS-PSC-Meeting-03-December-2018.pdf)
- [x] [QGIS-PSC-Meeting-05-November-2018.pdf](https://github.com/qgis/PSC/files/5866343/QGIS-PSC-Meeting-05-November-2018.pdf)
- [x] [QGIS-PSC-Meeting-01-October-2018.pdf](https://github.com/qgis/PSC/files/5866361/QGIS-PSC-Meeting-01-October-2018.pdf)
- [x] [QGIS-PSC-Meeting-10-September-2018.pdf](https://github.com/qgis/PSC/files/5866365/QGIS-PSC-Meeting-10-September-2018.pdf)
- [x] [QGIS-PSC-Meeting-06-August-2018.pdf](https://github.com/qgis/PSC/files/5866372/QGIS-PSC-Meeting-06-August-2018.pdf)
- [x] [QGIS-PSC-Meeting-02-July-2018.pdf](https://github.com/qgis/PSC/files/5866380/QGIS-PSC-Meeting-02-July-2018.pdf)
- [x] [QGIS-PSC-Meeting-06-June-2018.pdf](https://github.com/qgis/PSC/files/5866388/QGIS-PSC-Meeting-06-June-2018.pdf)
- [x] [QGIS-PSC-Meeting-05-May-2018.pdf](https://github.com/qgis/PSC/files/5866406/QGIS-PSC-Meeting-05-May-2018.pdf)
- [x] [QGIS-PSC-Meeting-April-2018.pdf](https://github.com/qgis/PSC/files/5866413/QGIS-PSC-Meeting-April-2018.pdf)
- [x] [QGIS-PSC-Meeting-March-2018.pdf](https://github.com/qgis/PSC/files/5866419/QGIS-PSC-Meeting-March-2018.pdf)
- [x] [QGIS-PSC-Meeting-02-February-2018.pdf](https://github.com/qgis/PSC/files/5866427/QGIS-PSC-Meeting-02-February-2018.pdf)
- [x] [QGIS-PSC-Meeting-01-January-2018.pdf](https://github.com/qgis/PSC/files/5866437/QGIS-PSC-Meeting-01-January-2018.pdf)



## 2017
- [x]  [QGIS-PSC-Meeting-December-2017.pdf](https://github.com/qgis/PSC/files/5855273/QGIS-PSC-Meeting-December-2017.pdf)
- [x] [QGIS-PSC-Meeting-November-2017.pdf](https://github.com/qgis/PSC/files/5855277/QGIS-PSC-Meeting-November-2017.pdf)
- [x] [QGIS-PSC-Meeting-October-2017.pdf](https://github.com/qgis/PSC/files/5855281/QGIS-PSC-Meeting-October-2017.pdf)
- [x] [QGIS-PSC-Meeting-September-2017.pdf](https://github.com/qgis/PSC/files/5855290/20170904-QGIS-PSC-Meeting-September-2017.pdf)
- [ ] [August 2017]()
- [x] [QGIS-PSC-Meeting-July-2017.pdf](https://github.com/qgis/PSC/files/5855305/QGIS-PSC-Meeting-July-2017.pdf)
- [x] [QGIS-PSC-Meeting-June-2017.pdf](https://github.com/qgis/PSC/files/5855316/QGIS-PSC-Meeting-June-2017.pdf)
- [x] [QGIS-PSC-Meeting-May-2017.pdf](https://github.com/qgis/PSC/files/5855329/QGIS-PSC-Meeting-May-2017.pdf)
- [x] [QGIS-PSC-Meeting-April-2017.pdf](https://github.com/qgis/PSC/files/5855338/20170405-QGIS-PSC-Meeting-April-2017.pdf)
- [x] [QGIS-PSC-Meeting-March-2017.pdf](https://github.com/qgis/PSC/files/5866304/QGIS-PSC-Meeting-March-2017.pdf)
- [ ] [February]()
- [x] [QGIS-PSC-Meeting-January-2017.pdf](https://github.com/qgis/PSC/files/5866317/QGIS-PSC-Meeting-January-2017.pdf)




## 2016
- [x] [QGIS-PSC-Meeting-December2016.pdf](https://github.com/qgis/PSC/files/5855032/QGIS-PSC-Meeting-December2016.pdf)
- [x] [QGIS-PSC-Meeting-November2016.pdf](https://github.com/qgis/PSC/files/5855042/QGIS-PSC-Meeting-November2016.pdf)
- [ ] [October 2016](https://docs.google.com/document/d/1STc6beUTtUjA6h_krobsS6F-jFbGVvTGGnGPmGMRtEA/edit) 
- [x] [QGIS-PSC-Meeting-September2016.pdf](https://github.com/qgis/PSC/files/6018393/QGIS-PSC-Meeting-September2016.pdf)
- [x] [QGIS-PSC-Meeting-August2016.pdf](https://github.com/qgis/PSC/files/5855107/QGIS-PSC-Meeting-August2016.pdf)
- [x] [QGIS-PSC-Meeting-July2016.pdf](https://github.com/qgis/PSC/files/5855127/QGIS-PSC-Meeting-July2016.pdf)
- [x] [QGIS-PSC-Meeting-June2016.pdf](https://github.com/qgis/PSC/files/5855133/QGIS-PSC-Meeting-June2016.pdf)
- [x] [QGIS-PSC-Meeting-May2016.pdf](https://github.com/qgis/PSC/files/5855141/QGIS-PSC-Meeting-May2016.pdf)
- [x] [QGIS-PSC-Meeting-April2016.pdf](https://github.com/qgis/PSC/files/5855150/QGIS-PSC-Meeting-April2016.pdf)
- [x] [QGIS-PSC-Meeting-March2016.pdf](https://github.com/qgis/PSC/files/5855157/QGIS-PSC-Meeting-March2016.pdf)
- [x] [QGIS-PSC-Meeting-February2016.pdf](https://github.com/qgis/PSC/files/5855169/QGIS-PSC-Meeting-February2016.pdf)
- [x] [QGIS-PSC-Meeting-January2016.pdf](https://github.com/qgis/PSC/files/5855183/QGIS-PSC-Meeting-January2016.pdf)

**Comment by seabilwe** [comment]
Hi @timlinux @anitagraser  I have converted all the files, except for the ones mentioned below. 

Access to files:
- [x] February  2017 PDF: [February 2017.pdf](https://github.com/qgis/PSC/files/7453228/February.2017.pdf)
- [x] August 2017 PDF: [August 2017.pdf](https://github.com/qgis/PSC/files/7453229/August.2017.pdf)


Documents not present: 
- [x] September 2016 PDF: [September 2016.pdf](https://github.com/qgis/PSC/files/7453230/September.2016.pdf)
- [x] October 2016 PDF: [October 2016.pdf](https://github.com/qgis/PSC/files/7453235/October.2016.pdf)
- [x] September 2019 PDF: [September 2019.pdf](https://github.com/qgis/PSC/files/7453242/September.2019.pdf)
- [x] July 2019 PDF: [July 2019.pdf](https://github.com/qgis/PSC/files/7453287/July.2019.pdf)

**Comment by timlinux** [comment]
Thank you so much @seabilwe

**Comment by timlinux** [comment]
@seabilwe can you move the pdf links above onto the wiki page?

**Comment by anitagraser** [comment]
@timlinux @seabilwe will you continue this effort in the future, i.e. will you set yourself a reminder to publish the minutes after each meeting? February 2021 and later are currently missing.

**Comment by anitagraser** [comment]
Concerning the missing missing files:

- September 2019: The September meeting was in late August (https://docs.google.com/document/d/1fecwgBHJ1VOGMpyf5QclIxmLJklvsc5a7Do_qKaWIos/edit?usp=sharing) and the August meeting was in late June. I've fixed the order: https://github.com/qgis/QGIS/wiki/Home/_compare/0b20828c75bc23dfc01eae06381cfac523f1dca9.
- What is actually missing from the PDFs is the July 1st 2019 meeting (https://docs.google.com/document/d/1gvJVA6FzZhak2W449SdhXVYRXCIv4a2XRjr6MPCdUvw/edit?usp=sharing)
- February 2017: I've fixed the sharing https://docs.google.com/document/d/1J-4smr-o_xQUoOUvLI1O-ge3sBczElthGwvSZiKU5ZY/edit?usp=sharing
- August 2017: I've fixed the sharing https://docs.google.com/document/d/1u7_dH_PmPj2hxP8_bnrDzL4z7bN7ZyCAT1ZWG4Tyg4M/edit?usp=sharing
- September 2016: https://docs.google.com/document/d/1iGxx7N587CxGiXGlVlvrBFW7tVXltY4XXbVogWYJbsg/edit?usp=sharing
- October 2016: https://docs.google.com/document/d/1WAssPzPoZBLOLQEolojqaSbpufa6qNXue13sbdLn4Ek/edit?usp=sharing

**Comment by seabilwe** [comment]
Hi @anitagraser @timlinux I will make some time during  the week and sort everything out
