### ISSUE TITLE
Add QGIS Application Network Connections to website

### ISSUE THREAD

**Issue by anitagraser** [qgis/PSC#55]
Deadline
===========
2021-12-12

Notes
=====

- [x] Prepare Overview document: [QGIS Application Network Connections](https://docs.google.com/document/d/1V0q1TIG6nhSwGFHa9-hG7duEuUHE0xOc3iEYN3cZKd4/edit#)
- [x] Add table to documentation https://docs.qgis.org/testing/en/docs/user_manual/appendices/qgis_desktop_network_connections.html
- [x] Publish link to documentation on the website in the “for users” section https://qgis.org/en/site/forusers/index.html

**Comment by anitagraser** [comment]
Since it's a big table, it needs more screen estate than qgis.org web pages provide. Therefore, I've decided to add this content to the user manual: https://github.com/qgis/QGIS-Documentation/pull/7178

**Comment by mbernasocchi** [comment]
@anitagraser I added the OS, but maybe @elpaso can check the original table?

**Comment by elpaso** [comment]
> @anitagraser I added the OS, but maybe @elpaso can check the original table?

LGTM, the OS has been added where relevant.

**Comment by anitagraser** [comment]
The table PR has been merged into docs. Once the docs are rendered, we are ready to put the link to the new appendix https://docs.qgis.org/testing/en/docs/user_manual/appendices/index.html on the QGIS website.

**Comment by agiudiceandrea** [comment]
Hi @anitagraser, in the file https://docs.google.com/document/d/1V0q1TIG6nhSwGFHa9-hG7duEuUHE0xOc3iEYN3cZKd4 I see "**IP, QGIS version, OS**" as information sent to the server, while in https://docs.qgis.org/testing/en/docs/user_manual/appendices/qgis_desktop_network_connections.html I see only "**IP, QGIS version**", so "**OS**" is missing.

Is this intended or is it an oversight?

See also https://github.com/qgis/QGIS/pull/46090

**Comment by anitagraser** [comment]
Hi Andrea,

That was certainly an oversight. Good catch and thank you for reporting it. I've updated the table: https://github.com/qgis/QGIS-Documentation/pull/7434

Regards,

Anita

**Comment by agiudiceandrea** [comment]
Hi @anitagraser, thanks!

It seems to me that probably there is something else missing or not clear: e.g., the table says that the information stored on qgis.org server is only the IP, so what's the reason of adding the OS (and the QGIS version) to the User-Agent string sent by QGIS Desktop client to the QGIS Web server? Is such information discarded, not used and not stored in the logs or is it anonymised/aggregated and stored?

It seems to me there is also no mention anywhere about what data are stored by the QGIS Web server when a user browse the Web site or downloads a QGIS installer: e.g. for MS Windows the download could be offered from one of the mirrors hosted by different servers as osgeo.org, norbit.de or osuosl.org.
Maybe this information could be written in a page of the QGIS Web site, instead of the Appendix E of the QGIS Desktop User Guide / Manual, since it is not specific to the QGIS Desktop client.

**Comment by anitagraser** [comment]
Yes, this table is only meant to describe the connections QGIS Desktop makes. 

> what's the reason of adding the OS (and the QGIS version) to the User-Agent string sent by QGIS Desktop client to the QGIS Web server? Is such information discarded, not used and not stored in the logs or is it anonymised/aggregated and stored?

It may be that the version info is used in the "New version check" but @mbernasocchi will know more. However, as far as I know, the information is discarded afterward. 

On the website, we have minimized the amount of cookies used. Some are necessary to provide donation options.

**Comment by agiudiceandrea** [comment]
> It may be that the version info is used in the "New version check" but @mbernasocchi will know more.

Yes, I know. Anyway, it seems to me the server for the "New version check" is `version.qgis.org`, not `www.qgis.org`, and that the QGIS version is sent also for "QGIS Feed", in addition to IP, language code, last download timestamp and OS.

Since the OS info is sent in order to "collect some statistics about the operating system" then I presume it is stored.
